homeassistant:
  # Details
  name: Holland House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 275
  unit_system: imperial
  time_zone: America/New_York

  customize: !include customize.yaml

# Enables
config:
http:
logger:
  default: error
updater:
history:
logbook:
# locattion
map:
# weather
sun:

# sensors
#binary_sensor: !include binary_sensor.yaml
sensor: !include_dir_merge_list sensors/

# includes
frontend: !include frontend.yaml
panel_custom: !include panel_custom.yaml
group: !include groups.yaml
automation: !include automation/automation.yaml
script: !include scripts.yaml
