title: My Awesome Home
views:
    # View tab title.
- title: Weather
    cards:
      - type: weather-forecast
        title: Weather
        entity: weather.yweather
      - type: entities
        title: Weather Alerts
        show_header_toggle: false
        entities:
          - entity: sensor.dupage_nws_alert_count
            name: Dupage Weather Alert Count
            icon: mdi:weather-lightning-rainy
          - entity: sensor.dupage_nws_alert_event
            name: Dupage Weather Alert
            icon: mdi:cloud-alert
          - entity: sensor.cook_nws_alert_count
            name: Cook Weather Alert Count
            icon: mdi:weather-lightning-rainy
          - entity: sensor.cook_nws_alert_event
            name: Cook Weather Alert
            icon: mdi:cloud-alert
      - type: entities
        title: Weather Forecast
        show_header_toggle: false
        entities:
          - entity: sensor.forecast_0
            icon: mdi:blank
          - entity: sensor.dark_sky_summary
            name: " "
          - entity: sensor.forecast_1
            icon: mdi:blank
          - entity: sensor.dark_sky_summary_1
            name: " "
          - entity: sensor.forecast_2
            icon: mdi:blank
          - entity: sensor.dark_sky_summary_2
            name: " "
          - entity: sensor.forecast_3
            icon: mdi:blank
          - entity: sensor.dark_sky_summary_3
            name: " "
          - entity: sensor.forecast_4
            icon: mdi:blank
          - entity: sensor.dark_sky_summary_4
            name: " "
          - entity: sensor.forecast_5
            icon: mdi:blank
          - entity: sensor.dark_sky_summary_5
            name: " "
          - entity: sensor.forecast_6
            icon: mdi:blank
          - entity: sensor.dark_sky_summary_6
            name: " "
          - entity: sensor.forecast_7
            icon: mdi:blank
          - entity: sensor.dark_sky_summary_7
            name: " "
      - type: iframe
        url: https://embed.windy.com/embed2.html?lat=41.965&lon=-88.190&zoom=11&level=surface&overlay=radar&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=41.943&detailLon=-88.145&metricWind=default&metricTemp=%C2%B0F&radarRange=-1
        aspect_ratio: 70%
